export const roomDetails = [
  {
    imgSrc: "/Hotel-img.png",
    name: "Raddison Blue Hotel and Suites",
    address: {
      area: "Surelere, Lagos",
      street: "Plot 37 Ahmed Onibudo Street",
    },
    roomType: "Deluxe Room",
    bedSpace: "1 bed (1 queen)",
    cancellation: "Free Cancellation",
    amenities: ["Free Wifi", "Air conditioning", "Pool", "Restaurant"],
    taxes: "Includes taxes and fees",
    price: "NGN 30,000",
    time: "avg/night",
    id: 1,
  },
  {
    imgSrc: "/Hotel-img.png",
    name: "Raddison Blue Hotel and Suites",
    address: {
      area: "Surelere, Lagos",
      street: "Plot 37 Ahmed Onibudo Street",
    },
    roomType: "Deluxe Room",
    bedSpace: "1 bed (1 queen)",
    cancellation: "Free Cancellation",
    amenities: ["Free Wifi", "Air conditioning", "Pool", "Restaurant"],
    taxes: "Includes taxes and fees",
    price: "NGN 30,000",
    time: "avg/night",
    id: 2,
  },
  {
    imgSrc: "/Hotel-img.png",
    name: "Wintess",
    address: {
      area: "Awka, Anambra",
      street: "Plot 37 Ahmed Onibudo Street",
    },
    roomType: "Deluxe Room",
    bedSpace: "1 bed (1 queen)",
    cancellation: "Free Cancellation",
    amenities: ["Free Wifi", "Air conditioning", "Pool", "Restaurant"],
    taxes: "Includes taxes and fees",
    price: "NGN 30,000",
    time: "avg/night",
    id: 3,
  },
  {
    imgSrc: "/Hotel-img.png",
    name: "Wintess",
    address: {
      area: "Awka, Anambra",
      street: "Plot 37 Ahmed Onibudo Street",
    },
    roomType: "Deluxe Room",
    bedSpace: "1 bed (1 queen)",
    cancellation: "Free Cancellation",
    amenities: ["Free Wifi", "Air conditioning", "Pool", "Restaurant"],
    taxes: "Includes taxes and fees",
    price: "NGN 30,000",
    time: "avg/night",
    id: 4,
  },
  {
    imgSrc: "/Hotel-img.png",
    name: "Wintess",
    address: {
      area: "Awka, Anambra",
      street: "Plot 37 Ahmed Onibudo Street",
    },
    roomType: "Deluxe Room",
    bedSpace: "1 bed (1 queen)",
    cancellation: "Free Cancellation",
    amenities: ["Free Wifi", "Air conditioning", "Pool", "Restaurant"],
    taxes: "Includes taxes and fees",
    price: "NGN 30,000",
    time: "avg/night",
    id: 5,
  },
  {
    imgSrc: "/Hotel-img.png",
    name: "Wintess",
    address: {
      area: "Awka, Anambra",
      street: "Plot 37 Ahmed Onibudo Street",
    },
    roomType: "Deluxe Room",
    bedSpace: "1 bed (1 queen)",
    cancellation: "Free Cancellation",
    amenities: ["Free Wifi", "Air conditioning", "Pool", "Restaurant"],
    taxes: "Includes taxes and fees",
    price: "NGN 30,000",
    time: "avg/night",
    id: 6,
  },
  {
    imgSrc: "/Hotel-img.png",
    name: "Wintess",
    address: {
      area: "Awka, Anambra",
      street: "Plot 37 Ahmed Onibudo Street",
    },
    roomType: "Deluxe Room",
    bedSpace: "1 bed (1 queen)",
    cancellation: "Free Cancellation",
    amenities: ["Free Wifi", "Air conditioning", "Pool", "Restaurant"],
    taxes: "Includes taxes and fees",
    price: "NGN 30,000",
    time: "avg/night",
    id: 7,
  },
  {
    imgSrc: "/Hotel-img.png",
    name: "Wintess",
    address: {
      area: "Awka, Anambra",
      street: "Plot 37 Ahmed Onibudo Street",
    },
    roomType: "Deluxe Room",
    bedSpace: "1 bed (1 queen)",
    cancellation: "Free Cancellation",
    amenities: ["Free Wifi", "Air conditioning", "Pool", "Restaurant"],
    taxes: "Includes taxes and fees",
    price: "NGN 30,000",
    time: "avg/night",
    id: 8,
  },
  {
    imgSrc: "/Hotel-img.png",
    name: "Wintess",
    address: {
      area: "Awka, Anambra",
      street: "Plot 37 Ahmed Onibudo Street",
    },
    roomType: "Deluxe Room",
    bedSpace: "1 bed (1 queen)",
    cancellation: "Free Cancellation",
    amenities: ["Free Wifi", "Air conditioning", "Pool", "Restaurant"],
    taxes: "Includes taxes and fees",
    price: "NGN 30,000",
    time: "avg/night",
    id: 9,
  },
];
