name: Development Pipeline

on:
  push:
    branches: [ devl ]

jobs:

  build_image:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD 
    - name: Build the Docker image
      run: docker build -t prestigegodson/africanvo-frontend-dev:latest --build-arg environment=Development .
      
    - name: Docker Push
      run: docker push prestigegodson/africanvo-frontend-dev:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_image

    steps:
      - name: Deploy to Digital Ocean droplet via SSH action
        if: always()
        uses: appleboy/ssh-action@v0.1.3
        with:
            host: ${{ secrets.SSH_HOST }}
            username: ${{ secrets.SSH_USER }}
            password: ${{ secrets.SSH_PASSWORD }}
            envs: IMAGE_NAME,GITHUB_SHA
            command_timeout: 12m
            script: |
              
              docker pull prestigegodson/africanvo-frontend-dev
            
              # Stop running container
              docker stop AFRICAN_VO_FRONTEND || true

              # Remove old container
              docker rm AFRICAN_VO_FRONTEND

              # Run a new container from a new image
              docker run -d \
              --restart always \
              -p 3000:3000 \
              --name AFRICAN_VO_FRONTEND \
              prestigegodson/africanvo-frontend-dev
